extends:
  - stylelint-config-html/vue
  - stylelint-config-standard
  - stylelint-config-recommended-scss
  - stylelint-config-recommended-vue
  - stylelint-config-prettier
plugins:
  - stylelint-prettier
rules:
  prettier/prettier: true
  color-function-notation: legacy
  selector-class-pattern: null
  no-descending-specificity: null
  at-rule-no-unknown: null
  scss/no-global-function-names: null
